### ISSUE TITLE
Update to 1.3.3?

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#11]
When I look at https://github.com/iyoua/Family-Trees-List/blob/main/TreesListModule.php there is still 1.3.2. In version.txt there is 1.3.2. The line "->whereNotIn('d_fact', ['HAED', 'CHAN']) // 排除HAED和CHAN" there is still HAED instead of HEAD.

**Comment by hartenthaler** [comment]
I downloaded now 1.3.3 from the releases. In the file TreeListModule.php in line 147 there is still an error: it should be HEAD (not HAED and not HEDD).

**Comment by iyoua** [comment]
Please test the complete code I sent to your email, thank you!
