### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#2]
Thank you for adding the German translation already. I have some minor change requests:

```
    protected function germanTranslations(): array
    {
        // Note the special characters used in plural and context-sensitive translations.
        return [
            'List of FamilyTree on Website' => 'Liste der Stammbäume auf dieser Website',
            'Total number of households' => 'Gesamtzahl der Familie',
            'Total number of Individuals' => 'Gesamtzahl der Personen',
            'Total number of Events' => 'Gesamtzahl der Ereignisse',
            'Total number of Surnames' => 'Gesamtzahl der Nachnamen',
            'FamilyTree List' => 'Stammbaum-Liste',
        ];
    }
```

**Comment by hartenthaler** [comment]
Oh, I just saw an error in the second element of that array: it should be 

Gesamtzahl der Familien

instead of 

Gesamtzahl der Familie

**Comment by iyoua** [comment]
protected function germanTranslations(): array
    {
        // Note the special characters used in plural and context-sensitive translations.
        return [
            'This website has %s trees' => 'Diese Website hat %s Stammbäume',
            'There is one tree on this website'=>'Es gibt einen Baum auf dieser Website',
            'Total number of households' => 'Gesamtzahl der Familien',
            'Total number of Individuals' => 'Gesamtzahl der Personen',
            'Total number of Events' => 'Gesamtzahl der Ereignisse',
            'Total number of Surnames' => 'Gesamtzahl der Nachnamen',
            'FamilyTree List' => 'Stammbaum-Liste',
        ];
    }
