### ISSUE TITLE
Number of events

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#5]
Your module shows for one of my trees:
-  38122 events

However, the statistics block of this tree shows only 21755 events. All other values are correct. Do you use another interpretation of "event"?

**Comment by iyoua** [comment]
I changed the event count field d_file to d_fact, but I'm not sure if the result is correct. This number has not changed on my website.

**Comment by hartenthaler** [comment]
I do not know if your number is correct or if the number of events in the statistics block is accurate, but they are still different. Maybe you can check how webtrees calculates the number of events in the statistics block.

**Comment by iyoua** [comment]
Initially, I searched for statistical fields in the forum to see if I could find a way to customize them. After seeing this post on the forum, I decided to write this module. The code from FISHAREBEST makes me feel that the method is approaching:
`SELECT
gedcom_name,
(SELECT COUNT(*) FROM wt_individuals WHERE gedcom_id=i_file) AS Individuals,
(SELECT COUNT(*) FROM wt_families WHERE gedcom_id=f_file) AS Families,
(SELECT COUNT(*) FROM wt_sources WHERE gedcom_id=s_file) AS Sources,
(SELECT COUNT(*) FROM wt_media WHERE gedcom_id=m_file) AS Media,
(SELECT COUNT(*) FROM wt_other WHERE gedcom_id=o_file AND o_type='REPO') AS Repositories,
(SELECT COUNT(*) FROM wt_dates WHERE gedcom_id=d_file) AS Events,
(SELECT COUNT(DISTINCT n_surn) FROM wt_name WHERE gedcom_id=n_file) AS Surnames,
(SELECT page_count FROM wt_hit_counter WHERE wt_gedcom.gedcom_id=wt_hit_counter.gedcom_id AND page_name='index.php' AND page_parameter LIKE 'gedcom:%') AS Hits
FROM wt_gedcom
WHERE gedcom_id > 0
ORDER BY gedcom_name;`
His code is to count all the records in the date table as events, and that's how my event field came about.
[Code source](https://www.webtrees.net/index.php/forum/help-for-1-7/34438-solved-procedure-for-statistical-numbers-wanted#77339)

**Comment by iyoua** [comment]
Perhaps this statistical result should be called "facts and events".

**Comment by iyoua** [comment]
Fixed the issue of counting the number of events.

**Comment by hartenthaler** [comment]
in your code you use HAED instead of HEAD.

**Comment by iyoua** [comment]
Fixed in the new version.
