### ISSUE TITLE
Layout of block in left column

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#6]
If your block is shown in the left column there are two layout problems
- last list element too long
- if the tree title is too long the numbers are outside of the box.

![Screenshot (238)](https://github.com/iyoua/Family-Trees-List/assets/6324175/0d0b500b-08a1-4116-adfd-a7b35a136ea7)

**Comment by iyoua** [comment]
Your suggestions are all very good! I have also made changes to your suggestion on translating German, and will release an update next time.
My initial purpose in writing this module was to provide a prominent navigation to other genealogies on the default homepage of the website, allowing beginners to visit and learn from the default genealogy. The default family tree homepage is also the homepage of the website, which needs to undertake more statistical and display functions. Although the menu can also be navigated, it is not easy for beginners to see. Of course, if users are interested in other genealogies, they can also add this block to "My Page", and I am willing to change this setting to True
I have limited programming skills and am still constantly imitating and learning. I plan to add a setting option to this module in the future, where users can choose the display style of this list.





铁水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iyoua/Family-Trees-List"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 晚上10:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[iyoua/Family-Trees-List] Layout of block in left column (Issue #6)





 
If your block is shown in the left column there are two layout problems
  
last list element too long
 
if the tree title is too long the numbers are outside of the box.
  
Screenshot.238.png (view on web)

**Comment by iyoua** [comment]
Chinese family tree names usually do not exceed one row, and my homepage is displayed as one or two columns, so I did not consider situations where there are more than two columns. Perhaps changing the template to CARD format would be more suitable. Next time, come and modify this template.

**Comment by iyoua** [comment]
Can you accept this layout?
![20240516085734](https://github.com/iyoua/Family-Trees-List/assets/102014216/7204fea2-96fc-4fde-93e8-e3597d877d06)

**Comment by hartenthaler** [comment]
For me, this is solved now. Thank you!
