### ISSUE TITLE
Translation singular/plural

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#8]
Instead of using "if" and "else" when translating singular/plural like in 
`I18N::translate('There is one tree on this website');`
you can use
`I18N::plural('There is one tree on this website.',  'There are %d trees on this website.', $totaltrees, $totaltrees)`

**Comment by iyoua** [comment]
I used "I18N:: plural ('There is one tree on this website. ',' There are% d trees on this website. ', $totaltrees, $totaltrees)", and the result was "This website has 7 trees", not the desired "本网站有7个家谱".
why?

**Comment by iyoua** [comment]
Okay, I have learned how to write your extended family module and can translate it normally. Thank you!
