### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by hartenthaler** [iyoua/Family-Trees-List#9]
The module description (string in line 84) is not translated:
`List of FamilyTree on Website`

In my opinion, it should be 'List of Trees on this Website'. The German translation would be 'Liste der Stammbäume auf dieser Website'.

**Comment by iyoua** [comment]
The translation for this sentence has been added.

**Comment by iyoua** [comment]
1.3.0 Version Update
---------------------
Added block setting function,
Three display styles have been added,
Simplified prompt information and removed too many translation entries.
